name: Run Pa11y on Schedule

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-pa11y:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install pa11y
        run: npm install -g pa11y-ci

      - name: Generate Pa11y config
        env:
          NODE_ENV: production
          PROD_URL: ${{ secrets.FE_PROD_URL }}
        run: node pa11y/generatePa11yConfig.js

      - name: Print Pa11y config
        run: cat pa11yConfig.json

      - name: Run Pa11y CI
        run: npx pa11y-ci --config pa11yConfig.json
